Metrics/AbcSize:
  Enabled: false
Metrics/MethodLength:
  Enabled: false
Naming/VariableNumber:
  Enabled: false
Naming/MethodParameterName:
  Enabled: false
Naming/VariableName:
  Enabled: false
Metrics/ClassLength:
  Enabled: false
AllCops:
    NewCops: enable
